// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/grpc/helloworld.proto

package grpc;

public interface GetHelloWorldRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.GetHelloWorldRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
