// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/grpc/helloworld.proto

package grpc;

public interface HelloWorldResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.HelloWorldResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
